// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// maipow
arma::mat maipow(arma::mat a, arma::mat b);
RcppExport SEXP _VBEMM_maipow(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(maipow(a, b));
    return rcpp_result_gen;
END_RCPP
}
// rowprod
arma::vec rowprod(arma::mat a, arma::mat b);
RcppExport SEXP _VBEMM_rowprod(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rowprod(a, b));
    return rcpp_result_gen;
END_RCPP
}
// sigmod
double sigmod(double x);
RcppExport SEXP _VBEMM_sigmod(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(sigmod(x));
    return rcpp_result_gen;
END_RCPP
}
// Sigmod
arma::mat Sigmod(arma::mat x);
RcppExport SEXP _VBEMM_Sigmod(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Sigmod(x));
    return rcpp_result_gen;
END_RCPP
}
// LA1dima
double LA1dima(double x);
RcppExport SEXP _VBEMM_LA1dima(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(LA1dima(x));
    return rcpp_result_gen;
END_RCPP
}
// LAmatrix
arma::mat LAmatrix(arma::mat x);
RcppExport SEXP _VBEMM_LAmatrix(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(LAmatrix(x));
    return rcpp_result_gen;
END_RCPP
}
// Trans_10to2_mat
arma::mat Trans_10to2_mat(int K, const arma::ivec& CL);
RcppExport SEXP _VBEMM_Trans_10to2_mat(SEXP KSEXP, SEXP CLSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type CL(CLSEXP);
    rcpp_result_gen = Rcpp::wrap(Trans_10to2_mat(K, CL));
    return rcpp_result_gen;
END_RCPP
}
// H_allprofile_dina
arma::mat H_allprofile_dina(arma::mat alfa, arma::mat Q);
RcppExport SEXP _VBEMM_H_allprofile_dina(SEXP alfaSEXP, SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type alfa(alfaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(H_allprofile_dina(alfa, Q));
    return rcpp_result_gen;
END_RCPP
}
// H_allprofile_dina_oneitem
arma::vec H_allprofile_dina_oneitem(arma::mat alfa, arma::vec Q);
RcppExport SEXP _VBEMM_H_allprofile_dina_oneitem(SEXP alfaSEXP, SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type alfa(alfaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(H_allprofile_dina_oneitem(alfa, Q));
    return rcpp_result_gen;
END_RCPP
}
// H_allprofile_dino
arma::mat H_allprofile_dino(arma::mat alfa, arma::mat Q);
RcppExport SEXP _VBEMM_H_allprofile_dino(SEXP alfaSEXP, SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type alfa(alfaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(H_allprofile_dino(alfa, Q));
    return rcpp_result_gen;
END_RCPP
}
// H_allprofile_lcdm
arma::cube H_allprofile_lcdm(arma::mat alfa, arma::mat Q, arma::umat comb, arma::ivec leng);
RcppExport SEXP _VBEMM_H_allprofile_lcdm(SEXP alfaSEXP, SEXP QSEXP, SEXP combSEXP, SEXP lengSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type alfa(alfaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type comb(combSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type leng(lengSEXP);
    rcpp_result_gen = Rcpp::wrap(H_allprofile_lcdm(alfa, Q, comb, leng));
    return rcpp_result_gen;
END_RCPP
}
// H_allprofile_oneitem_lcdm
arma::mat H_allprofile_oneitem_lcdm(arma::mat alfa, arma::vec Q, arma::umat comb, arma::ivec leng);
RcppExport SEXP _VBEMM_H_allprofile_oneitem_lcdm(SEXP alfaSEXP, SEXP QSEXP, SEXP combSEXP, SEXP lengSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type alfa(alfaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type comb(combSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type leng(lengSEXP);
    rcpp_result_gen = Rcpp::wrap(H_allprofile_oneitem_lcdm(alfa, Q, comb, leng));
    return rcpp_result_gen;
END_RCPP
}
// ke_1dim
arma::mat ke_1dim(arma::cube h, arma::mat lambda, arma::cube Vlambda);
RcppExport SEXP _VBEMM_ke_1dim(SEXP hSEXP, SEXP lambdaSEXP, SEXP VlambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type h(hSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Vlambda(VlambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(ke_1dim(h, lambda, Vlambda));
    return rcpp_result_gen;
END_RCPP
}
// update_lcdm
void update_lcdm(arma::mat y, arma::cube h, arma::mat& lambda, arma::cube& Vlambda, arma::mat& xi, arma::vec& phi1, arma::vec& phi2, arma::vec& delta0, arma::vec& delta, arma::mat& rho, arma::vec& lambda0, arma::mat& Vlambda0, arma::umat& lambdaindd, arma::ivec& lambdalen);
RcppExport SEXP _VBEMM_update_lcdm(SEXP ySEXP, SEXP hSEXP, SEXP lambdaSEXP, SEXP VlambdaSEXP, SEXP xiSEXP, SEXP phi1SEXP, SEXP phi2SEXP, SEXP delta0SEXP, SEXP deltaSEXP, SEXP rhoSEXP, SEXP lambda0SEXP, SEXP Vlambda0SEXP, SEXP lambdainddSEXP, SEXP lambdalenSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::cube >::type h(hSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type Vlambda(VlambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type phi1(phi1SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type phi2(phi2SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type delta0(delta0SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type lambda0(lambda0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Vlambda0(Vlambda0SEXP);
    Rcpp::traits::input_parameter< arma::umat& >::type lambdaindd(lambdainddSEXP);
    Rcpp::traits::input_parameter< arma::ivec& >::type lambdalen(lambdalenSEXP);
    update_lcdm(y, h, lambda, Vlambda, xi, phi1, phi2, delta0, delta, rho, lambda0, Vlambda0, lambdaindd, lambdalen);
    return R_NilValue;
END_RCPP
}
// ELBO_1dim
double ELBO_1dim(arma::mat y, arma::cube Vlambda, arma::mat xi, arma::mat rho, arma::mat Vlambda0, arma::vec delta, arma::vec delta0, arma::vec lambda00, arma::vec Vlambda00, arma::vec lambda0t, arma::vec Vlambda0t, double ph0, double pht, double df);
RcppExport SEXP _VBEMM_ELBO_1dim(SEXP ySEXP, SEXP VlambdaSEXP, SEXP xiSEXP, SEXP rhoSEXP, SEXP Vlambda0SEXP, SEXP deltaSEXP, SEXP delta0SEXP, SEXP lambda00SEXP, SEXP Vlambda00SEXP, SEXP lambda0tSEXP, SEXP Vlambda0tSEXP, SEXP ph0SEXP, SEXP phtSEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Vlambda(VlambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Vlambda0(Vlambda0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta0(delta0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda00(lambda00SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Vlambda00(Vlambda00SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda0t(lambda0tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Vlambda0t(Vlambda0tSEXP);
    Rcpp::traits::input_parameter< double >::type ph0(ph0SEXP);
    Rcpp::traits::input_parameter< double >::type pht(phtSEXP);
    Rcpp::traits::input_parameter< double >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(ELBO_1dim(y, Vlambda, xi, rho, Vlambda0, delta, delta0, lambda00, Vlambda00, lambda0t, Vlambda0t, ph0, pht, df));
    return rcpp_result_gen;
END_RCPP
}
// ELBO_lcdm
double ELBO_lcdm(arma::mat y, arma::cube Vlambda, arma::mat xi, arma::mat rho, arma::mat Vlambda0, arma::vec delta, arma::vec delta0, arma::umat lambdaindd, arma::ivec lambdalen, arma::vec Mlambda0, arma::vec VMlambda0, arma::vec Mlambda0t, arma::vec VMlambda0t, arma::vec ph0, arma::vec pht, arma::vec df);
RcppExport SEXP _VBEMM_ELBO_lcdm(SEXP ySEXP, SEXP VlambdaSEXP, SEXP xiSEXP, SEXP rhoSEXP, SEXP Vlambda0SEXP, SEXP deltaSEXP, SEXP delta0SEXP, SEXP lambdainddSEXP, SEXP lambdalenSEXP, SEXP Mlambda0SEXP, SEXP VMlambda0SEXP, SEXP Mlambda0tSEXP, SEXP VMlambda0tSEXP, SEXP ph0SEXP, SEXP phtSEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Vlambda(VlambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Vlambda0(Vlambda0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta0(delta0SEXP);
    Rcpp::traits::input_parameter< arma::umat >::type lambdaindd(lambdainddSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type lambdalen(lambdalenSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Mlambda0(Mlambda0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type VMlambda0(VMlambda0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Mlambda0t(Mlambda0tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type VMlambda0t(VMlambda0tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ph0(ph0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pht(phtSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(ELBO_lcdm(y, Vlambda, xi, rho, Vlambda0, delta, delta0, lambdaindd, lambdalen, Mlambda0, VMlambda0, Mlambda0t, VMlambda0t, ph0, pht, df));
    return rcpp_result_gen;
END_RCPP
}
// ELBO_lcdm_main_inter
double ELBO_lcdm_main_inter(arma::mat y, arma::cube Vlambda, arma::mat xi, arma::mat rho, arma::mat Vlambda0, arma::vec delta, arma::vec delta0, arma::umat lambdaindd, arma::ivec lambdalen, arma::vec Mlambda0, arma::vec VMlambda0, arma::vec Mlambda0t, arma::vec VMlambda0t, arma::vec ph0, arma::vec pht, arma::vec df);
RcppExport SEXP _VBEMM_ELBO_lcdm_main_inter(SEXP ySEXP, SEXP VlambdaSEXP, SEXP xiSEXP, SEXP rhoSEXP, SEXP Vlambda0SEXP, SEXP deltaSEXP, SEXP delta0SEXP, SEXP lambdainddSEXP, SEXP lambdalenSEXP, SEXP Mlambda0SEXP, SEXP VMlambda0SEXP, SEXP Mlambda0tSEXP, SEXP VMlambda0tSEXP, SEXP ph0SEXP, SEXP phtSEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Vlambda(VlambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Vlambda0(Vlambda0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta0(delta0SEXP);
    Rcpp::traits::input_parameter< arma::umat >::type lambdaindd(lambdainddSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type lambdalen(lambdalenSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Mlambda0(Mlambda0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type VMlambda0(VMlambda0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Mlambda0t(Mlambda0tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type VMlambda0t(VMlambda0tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ph0(ph0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pht(phtSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(ELBO_lcdm_main_inter(y, Vlambda, xi, rho, Vlambda0, delta, delta0, lambdaindd, lambdalen, Mlambda0, VMlambda0, Mlambda0t, VMlambda0t, ph0, pht, df));
    return rcpp_result_gen;
END_RCPP
}
// digamma_vec
arma::vec digamma_vec(arma::vec a);
RcppExport SEXP _VBEMM_digamma_vec(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(digamma_vec(a));
    return rcpp_result_gen;
END_RCPP
}
// Estimate_alpha
arma::mat Estimate_alpha(arma::mat rho, arma::mat alpha_all, int N, int K);
RcppExport SEXP _VBEMM_Estimate_alpha(SEXP rhoSEXP, SEXP alpha_allSEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alpha_all(alpha_allSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(Estimate_alpha(rho, alpha_all, N, K));
    return rcpp_result_gen;
END_RCPP
}
// VBEMM_DINA
Rcpp::List VBEMM_DINA(arma::mat data, int K, arma::mat Q, double EMlambda0, double Vlambda0_value, double EMeta0, double delta0_value, double ueta0, double ulambda0, double veta0, double vlambda0, double Mlambdainitial, double Vlambdainitial_value, double Metainitial, double deltainitial, double trunc_num, int T, double e0);
RcppExport SEXP _VBEMM_VBEMM_DINA(SEXP dataSEXP, SEXP KSEXP, SEXP QSEXP, SEXP EMlambda0SEXP, SEXP Vlambda0_valueSEXP, SEXP EMeta0SEXP, SEXP delta0_valueSEXP, SEXP ueta0SEXP, SEXP ulambda0SEXP, SEXP veta0SEXP, SEXP vlambda0SEXP, SEXP MlambdainitialSEXP, SEXP Vlambdainitial_valueSEXP, SEXP MetainitialSEXP, SEXP deltainitialSEXP, SEXP trunc_numSEXP, SEXP TSEXP, SEXP e0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< double >::type EMlambda0(EMlambda0SEXP);
    Rcpp::traits::input_parameter< double >::type Vlambda0_value(Vlambda0_valueSEXP);
    Rcpp::traits::input_parameter< double >::type EMeta0(EMeta0SEXP);
    Rcpp::traits::input_parameter< double >::type delta0_value(delta0_valueSEXP);
    Rcpp::traits::input_parameter< double >::type ueta0(ueta0SEXP);
    Rcpp::traits::input_parameter< double >::type ulambda0(ulambda0SEXP);
    Rcpp::traits::input_parameter< double >::type veta0(veta0SEXP);
    Rcpp::traits::input_parameter< double >::type vlambda0(vlambda0SEXP);
    Rcpp::traits::input_parameter< double >::type Mlambdainitial(MlambdainitialSEXP);
    Rcpp::traits::input_parameter< double >::type Vlambdainitial_value(Vlambdainitial_valueSEXP);
    Rcpp::traits::input_parameter< double >::type Metainitial(MetainitialSEXP);
    Rcpp::traits::input_parameter< double >::type deltainitial(deltainitialSEXP);
    Rcpp::traits::input_parameter< double >::type trunc_num(trunc_numSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type e0(e0SEXP);
    rcpp_result_gen = Rcpp::wrap(VBEMM_DINA(data, K, Q, EMlambda0, Vlambda0_value, EMeta0, delta0_value, ueta0, ulambda0, veta0, vlambda0, Mlambdainitial, Vlambdainitial_value, Metainitial, deltainitial, trunc_num, T, e0));
    return rcpp_result_gen;
END_RCPP
}
// VBEMM_DINO
Rcpp::List VBEMM_DINO(arma::mat data, int K, arma::mat Q, double EMlambda0, double Vlambda0_value, double EMeta0, double delta0_value, double ueta0, double ulambda0, double veta0, double vlambda0, double Mlambdainitial, double Vlambdainitial_value, double Metainitial, double deltainitial, double trunc_num, int T, double e0);
RcppExport SEXP _VBEMM_VBEMM_DINO(SEXP dataSEXP, SEXP KSEXP, SEXP QSEXP, SEXP EMlambda0SEXP, SEXP Vlambda0_valueSEXP, SEXP EMeta0SEXP, SEXP delta0_valueSEXP, SEXP ueta0SEXP, SEXP ulambda0SEXP, SEXP veta0SEXP, SEXP vlambda0SEXP, SEXP MlambdainitialSEXP, SEXP Vlambdainitial_valueSEXP, SEXP MetainitialSEXP, SEXP deltainitialSEXP, SEXP trunc_numSEXP, SEXP TSEXP, SEXP e0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< double >::type EMlambda0(EMlambda0SEXP);
    Rcpp::traits::input_parameter< double >::type Vlambda0_value(Vlambda0_valueSEXP);
    Rcpp::traits::input_parameter< double >::type EMeta0(EMeta0SEXP);
    Rcpp::traits::input_parameter< double >::type delta0_value(delta0_valueSEXP);
    Rcpp::traits::input_parameter< double >::type ueta0(ueta0SEXP);
    Rcpp::traits::input_parameter< double >::type ulambda0(ulambda0SEXP);
    Rcpp::traits::input_parameter< double >::type veta0(veta0SEXP);
    Rcpp::traits::input_parameter< double >::type vlambda0(vlambda0SEXP);
    Rcpp::traits::input_parameter< double >::type Mlambdainitial(MlambdainitialSEXP);
    Rcpp::traits::input_parameter< double >::type Vlambdainitial_value(Vlambdainitial_valueSEXP);
    Rcpp::traits::input_parameter< double >::type Metainitial(MetainitialSEXP);
    Rcpp::traits::input_parameter< double >::type deltainitial(deltainitialSEXP);
    Rcpp::traits::input_parameter< double >::type trunc_num(trunc_numSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type e0(e0SEXP);
    rcpp_result_gen = Rcpp::wrap(VBEMM_DINO(data, K, Q, EMlambda0, Vlambda0_value, EMeta0, delta0_value, ueta0, ulambda0, veta0, vlambda0, Mlambdainitial, Vlambdainitial_value, Metainitial, deltainitial, trunc_num, T, e0));
    return rcpp_result_gen;
END_RCPP
}
// VBEMM_LCDM
Rcpp::List VBEMM_LCDM(arma::mat data, int K, arma::mat Q, arma::umat lambdaindex, arma::umat comb, arma::ivec comlen, double EMlambda0_value, double Vlambda0_value, double EMeta0, double delta0_value, double ueta0, double ulambda0, double veta0, double vlambda0, double Mlambdainitial, double Vlambdainitial_value, double Metainitial, double deltainitial, int T, double e0);
RcppExport SEXP _VBEMM_VBEMM_LCDM(SEXP dataSEXP, SEXP KSEXP, SEXP QSEXP, SEXP lambdaindexSEXP, SEXP combSEXP, SEXP comlenSEXP, SEXP EMlambda0_valueSEXP, SEXP Vlambda0_valueSEXP, SEXP EMeta0SEXP, SEXP delta0_valueSEXP, SEXP ueta0SEXP, SEXP ulambda0SEXP, SEXP veta0SEXP, SEXP vlambda0SEXP, SEXP MlambdainitialSEXP, SEXP Vlambdainitial_valueSEXP, SEXP MetainitialSEXP, SEXP deltainitialSEXP, SEXP TSEXP, SEXP e0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type lambdaindex(lambdaindexSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type comb(combSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type comlen(comlenSEXP);
    Rcpp::traits::input_parameter< double >::type EMlambda0_value(EMlambda0_valueSEXP);
    Rcpp::traits::input_parameter< double >::type Vlambda0_value(Vlambda0_valueSEXP);
    Rcpp::traits::input_parameter< double >::type EMeta0(EMeta0SEXP);
    Rcpp::traits::input_parameter< double >::type delta0_value(delta0_valueSEXP);
    Rcpp::traits::input_parameter< double >::type ueta0(ueta0SEXP);
    Rcpp::traits::input_parameter< double >::type ulambda0(ulambda0SEXP);
    Rcpp::traits::input_parameter< double >::type veta0(veta0SEXP);
    Rcpp::traits::input_parameter< double >::type vlambda0(vlambda0SEXP);
    Rcpp::traits::input_parameter< double >::type Mlambdainitial(MlambdainitialSEXP);
    Rcpp::traits::input_parameter< double >::type Vlambdainitial_value(Vlambdainitial_valueSEXP);
    Rcpp::traits::input_parameter< double >::type Metainitial(MetainitialSEXP);
    Rcpp::traits::input_parameter< double >::type deltainitial(deltainitialSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type e0(e0SEXP);
    rcpp_result_gen = Rcpp::wrap(VBEMM_LCDM(data, K, Q, lambdaindex, comb, comlen, EMlambda0_value, Vlambda0_value, EMeta0, delta0_value, ueta0, ulambda0, veta0, vlambda0, Mlambdainitial, Vlambdainitial_value, Metainitial, deltainitial, T, e0));
    return rcpp_result_gen;
END_RCPP
}
// VBEMM_LCDM_by_dim
Rcpp::List VBEMM_LCDM_by_dim(arma::mat data, int K, arma::mat Q, arma::umat lambdaindex, arma::umat comb, arma::ivec comlen, double EMlambda0_value, double Vlambda0_value, double EMeta0, double delta0_value, double ueta0, double ulambda0, double veta0, double vlambda0, double Mlambdainitial, double Vlambdainitial_value, double Metainitial, double deltainitial, double trunc_num, int T, double e0);
RcppExport SEXP _VBEMM_VBEMM_LCDM_by_dim(SEXP dataSEXP, SEXP KSEXP, SEXP QSEXP, SEXP lambdaindexSEXP, SEXP combSEXP, SEXP comlenSEXP, SEXP EMlambda0_valueSEXP, SEXP Vlambda0_valueSEXP, SEXP EMeta0SEXP, SEXP delta0_valueSEXP, SEXP ueta0SEXP, SEXP ulambda0SEXP, SEXP veta0SEXP, SEXP vlambda0SEXP, SEXP MlambdainitialSEXP, SEXP Vlambdainitial_valueSEXP, SEXP MetainitialSEXP, SEXP deltainitialSEXP, SEXP trunc_numSEXP, SEXP TSEXP, SEXP e0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type lambdaindex(lambdaindexSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type comb(combSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type comlen(comlenSEXP);
    Rcpp::traits::input_parameter< double >::type EMlambda0_value(EMlambda0_valueSEXP);
    Rcpp::traits::input_parameter< double >::type Vlambda0_value(Vlambda0_valueSEXP);
    Rcpp::traits::input_parameter< double >::type EMeta0(EMeta0SEXP);
    Rcpp::traits::input_parameter< double >::type delta0_value(delta0_valueSEXP);
    Rcpp::traits::input_parameter< double >::type ueta0(ueta0SEXP);
    Rcpp::traits::input_parameter< double >::type ulambda0(ulambda0SEXP);
    Rcpp::traits::input_parameter< double >::type veta0(veta0SEXP);
    Rcpp::traits::input_parameter< double >::type vlambda0(vlambda0SEXP);
    Rcpp::traits::input_parameter< double >::type Mlambdainitial(MlambdainitialSEXP);
    Rcpp::traits::input_parameter< double >::type Vlambdainitial_value(Vlambdainitial_valueSEXP);
    Rcpp::traits::input_parameter< double >::type Metainitial(MetainitialSEXP);
    Rcpp::traits::input_parameter< double >::type deltainitial(deltainitialSEXP);
    Rcpp::traits::input_parameter< double >::type trunc_num(trunc_numSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type e0(e0SEXP);
    rcpp_result_gen = Rcpp::wrap(VBEMM_LCDM_by_dim(data, K, Q, lambdaindex, comb, comlen, EMlambda0_value, Vlambda0_value, EMeta0, delta0_value, ueta0, ulambda0, veta0, vlambda0, Mlambdainitial, Vlambdainitial_value, Metainitial, deltainitial, trunc_num, T, e0));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _VBEMM_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_VBEMM_maipow", (DL_FUNC) &_VBEMM_maipow, 2},
    {"_VBEMM_rowprod", (DL_FUNC) &_VBEMM_rowprod, 2},
    {"_VBEMM_sigmod", (DL_FUNC) &_VBEMM_sigmod, 1},
    {"_VBEMM_Sigmod", (DL_FUNC) &_VBEMM_Sigmod, 1},
    {"_VBEMM_LA1dima", (DL_FUNC) &_VBEMM_LA1dima, 1},
    {"_VBEMM_LAmatrix", (DL_FUNC) &_VBEMM_LAmatrix, 1},
    {"_VBEMM_Trans_10to2_mat", (DL_FUNC) &_VBEMM_Trans_10to2_mat, 2},
    {"_VBEMM_H_allprofile_dina", (DL_FUNC) &_VBEMM_H_allprofile_dina, 2},
    {"_VBEMM_H_allprofile_dina_oneitem", (DL_FUNC) &_VBEMM_H_allprofile_dina_oneitem, 2},
    {"_VBEMM_H_allprofile_dino", (DL_FUNC) &_VBEMM_H_allprofile_dino, 2},
    {"_VBEMM_H_allprofile_lcdm", (DL_FUNC) &_VBEMM_H_allprofile_lcdm, 4},
    {"_VBEMM_H_allprofile_oneitem_lcdm", (DL_FUNC) &_VBEMM_H_allprofile_oneitem_lcdm, 4},
    {"_VBEMM_ke_1dim", (DL_FUNC) &_VBEMM_ke_1dim, 3},
    {"_VBEMM_update_lcdm", (DL_FUNC) &_VBEMM_update_lcdm, 14},
    {"_VBEMM_ELBO_1dim", (DL_FUNC) &_VBEMM_ELBO_1dim, 14},
    {"_VBEMM_ELBO_lcdm", (DL_FUNC) &_VBEMM_ELBO_lcdm, 16},
    {"_VBEMM_ELBO_lcdm_main_inter", (DL_FUNC) &_VBEMM_ELBO_lcdm_main_inter, 16},
    {"_VBEMM_digamma_vec", (DL_FUNC) &_VBEMM_digamma_vec, 1},
    {"_VBEMM_Estimate_alpha", (DL_FUNC) &_VBEMM_Estimate_alpha, 4},
    {"_VBEMM_VBEMM_DINA", (DL_FUNC) &_VBEMM_VBEMM_DINA, 18},
    {"_VBEMM_VBEMM_DINO", (DL_FUNC) &_VBEMM_VBEMM_DINO, 18},
    {"_VBEMM_VBEMM_LCDM", (DL_FUNC) &_VBEMM_VBEMM_LCDM, 20},
    {"_VBEMM_VBEMM_LCDM_by_dim", (DL_FUNC) &_VBEMM_VBEMM_LCDM_by_dim, 21},
    {"_VBEMM_rcpp_hello_world", (DL_FUNC) &_VBEMM_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_VBEMM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
