// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// maipow
arma::mat maipow(arma::mat a, arma::mat b);
RcppExport SEXP _VBEMM_maipow(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(maipow(a, b));
    return rcpp_result_gen;
END_RCPP
}
// rowprod
arma::vec rowprod(arma::mat a, arma::mat b);
RcppExport SEXP _VBEMM_rowprod(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rowprod(a, b));
    return rcpp_result_gen;
END_RCPP
}
// sigmod
double sigmod(double x);
RcppExport SEXP _VBEMM_sigmod(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(sigmod(x));
    return rcpp_result_gen;
END_RCPP
}
// Sigmod
arma::mat Sigmod(arma::mat x);
RcppExport SEXP _VBEMM_Sigmod(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Sigmod(x));
    return rcpp_result_gen;
END_RCPP
}
// LA1dima
double LA1dima(double x);
RcppExport SEXP _VBEMM_LA1dima(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(LA1dima(x));
    return rcpp_result_gen;
END_RCPP
}
// LAmatrix
arma::mat LAmatrix(arma::mat x);
RcppExport SEXP _VBEMM_LAmatrix(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(LAmatrix(x));
    return rcpp_result_gen;
END_RCPP
}
// H_allprofile_dina
arma::mat H_allprofile_dina(arma::mat alfa, arma::mat Q);
RcppExport SEXP _VBEMM_H_allprofile_dina(SEXP alfaSEXP, SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type alfa(alfaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(H_allprofile_dina(alfa, Q));
    return rcpp_result_gen;
END_RCPP
}
// H_allprofile_dino
arma::mat H_allprofile_dino(arma::mat alfa, arma::mat Q);
RcppExport SEXP _VBEMM_H_allprofile_dino(SEXP alfaSEXP, SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type alfa(alfaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(H_allprofile_dino(alfa, Q));
    return rcpp_result_gen;
END_RCPP
}
// H_allprofile_lcdm
arma::cube H_allprofile_lcdm(arma::mat alfa, arma::mat Q, arma::umat comb, arma::ivec leng);
RcppExport SEXP _VBEMM_H_allprofile_lcdm(SEXP alfaSEXP, SEXP QSEXP, SEXP combSEXP, SEXP lengSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type alfa(alfaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type comb(combSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type leng(lengSEXP);
    rcpp_result_gen = Rcpp::wrap(H_allprofile_lcdm(alfa, Q, comb, leng));
    return rcpp_result_gen;
END_RCPP
}
// ke_1dim
arma::mat ke_1dim(arma::cube h, arma::mat lambda, arma::cube Vlambda);
RcppExport SEXP _VBEMM_ke_1dim(SEXP hSEXP, SEXP lambdaSEXP, SEXP VlambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type h(hSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Vlambda(VlambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(ke_1dim(h, lambda, Vlambda));
    return rcpp_result_gen;
END_RCPP
}
// update
Rcpp::List update(arma::mat y, arma::cube h, arma::mat lambda, arma::cube Vlambda, arma::mat xi, arma::vec phi1, arma::vec phi2, arma::vec delta0, arma::vec lambda0, arma::mat Vlambda0);
RcppExport SEXP _VBEMM_update(SEXP ySEXP, SEXP hSEXP, SEXP lambdaSEXP, SEXP VlambdaSEXP, SEXP xiSEXP, SEXP phi1SEXP, SEXP phi2SEXP, SEXP delta0SEXP, SEXP lambda0SEXP, SEXP Vlambda0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::cube >::type h(hSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Vlambda(VlambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi1(phi1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi2(phi2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta0(delta0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda0(lambda0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Vlambda0(Vlambda0SEXP);
    rcpp_result_gen = Rcpp::wrap(update(y, h, lambda, Vlambda, xi, phi1, phi2, delta0, lambda0, Vlambda0));
    return rcpp_result_gen;
END_RCPP
}
// update_lcdm
Rcpp::List update_lcdm(arma::mat y, arma::cube h, arma::mat lambda, arma::cube Vlambda, arma::mat xi, arma::vec phi1, arma::vec phi2, arma::vec delta0, arma::vec lambda0, arma::mat Vlambda0, arma::umat lambdaindd, arma::ivec lambdalen);
RcppExport SEXP _VBEMM_update_lcdm(SEXP ySEXP, SEXP hSEXP, SEXP lambdaSEXP, SEXP VlambdaSEXP, SEXP xiSEXP, SEXP phi1SEXP, SEXP phi2SEXP, SEXP delta0SEXP, SEXP lambda0SEXP, SEXP Vlambda0SEXP, SEXP lambdainddSEXP, SEXP lambdalenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::cube >::type h(hSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Vlambda(VlambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi1(phi1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi2(phi2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta0(delta0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda0(lambda0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Vlambda0(Vlambda0SEXP);
    Rcpp::traits::input_parameter< arma::umat >::type lambdaindd(lambdainddSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type lambdalen(lambdalenSEXP);
    rcpp_result_gen = Rcpp::wrap(update_lcdm(y, h, lambda, Vlambda, xi, phi1, phi2, delta0, lambda0, Vlambda0, lambdaindd, lambdalen));
    return rcpp_result_gen;
END_RCPP
}
// ELBO_1dim
double ELBO_1dim(arma::mat y, arma::cube Vlambda, arma::mat xi, arma::mat rho, arma::mat Vlambda0, arma::vec delta, arma::vec delta0, arma::vec Mlambda0, arma::vec VMlambda0, arma::vec Mlambda0t, arma::vec VMlambda0t, double ph0, double pht, double df);
RcppExport SEXP _VBEMM_ELBO_1dim(SEXP ySEXP, SEXP VlambdaSEXP, SEXP xiSEXP, SEXP rhoSEXP, SEXP Vlambda0SEXP, SEXP deltaSEXP, SEXP delta0SEXP, SEXP Mlambda0SEXP, SEXP VMlambda0SEXP, SEXP Mlambda0tSEXP, SEXP VMlambda0tSEXP, SEXP ph0SEXP, SEXP phtSEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Vlambda(VlambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Vlambda0(Vlambda0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta0(delta0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Mlambda0(Mlambda0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type VMlambda0(VMlambda0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Mlambda0t(Mlambda0tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type VMlambda0t(VMlambda0tSEXP);
    Rcpp::traits::input_parameter< double >::type ph0(ph0SEXP);
    Rcpp::traits::input_parameter< double >::type pht(phtSEXP);
    Rcpp::traits::input_parameter< double >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(ELBO_1dim(y, Vlambda, xi, rho, Vlambda0, delta, delta0, Mlambda0, VMlambda0, Mlambda0t, VMlambda0t, ph0, pht, df));
    return rcpp_result_gen;
END_RCPP
}
// ELBO_lcdm
double ELBO_lcdm(arma::mat y, arma::cube Vlambda, arma::mat xi, arma::mat rho, arma::mat Vlambda0, arma::vec delta, arma::vec delta0, arma::umat lambdaindd, arma::ivec lambdalen, arma::vec Mlambda0, arma::vec VMlambda0, arma::vec Mlambda0t, arma::vec VMlambda0t, arma::vec ph0, arma::vec pht, arma::vec df);
RcppExport SEXP _VBEMM_ELBO_lcdm(SEXP ySEXP, SEXP VlambdaSEXP, SEXP xiSEXP, SEXP rhoSEXP, SEXP Vlambda0SEXP, SEXP deltaSEXP, SEXP delta0SEXP, SEXP lambdainddSEXP, SEXP lambdalenSEXP, SEXP Mlambda0SEXP, SEXP VMlambda0SEXP, SEXP Mlambda0tSEXP, SEXP VMlambda0tSEXP, SEXP ph0SEXP, SEXP phtSEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::cube >::type Vlambda(VlambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Vlambda0(Vlambda0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta0(delta0SEXP);
    Rcpp::traits::input_parameter< arma::umat >::type lambdaindd(lambdainddSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type lambdalen(lambdalenSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Mlambda0(Mlambda0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type VMlambda0(VMlambda0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Mlambda0t(Mlambda0tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type VMlambda0t(VMlambda0tSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ph0(ph0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pht(phtSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(ELBO_lcdm(y, Vlambda, xi, rho, Vlambda0, delta, delta0, lambdaindd, lambdalen, Mlambda0, VMlambda0, Mlambda0t, VMlambda0t, ph0, pht, df));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _VBEMM_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_VBEMM_maipow", (DL_FUNC) &_VBEMM_maipow, 2},
    {"_VBEMM_rowprod", (DL_FUNC) &_VBEMM_rowprod, 2},
    {"_VBEMM_sigmod", (DL_FUNC) &_VBEMM_sigmod, 1},
    {"_VBEMM_Sigmod", (DL_FUNC) &_VBEMM_Sigmod, 1},
    {"_VBEMM_LA1dima", (DL_FUNC) &_VBEMM_LA1dima, 1},
    {"_VBEMM_LAmatrix", (DL_FUNC) &_VBEMM_LAmatrix, 1},
    {"_VBEMM_H_allprofile_dina", (DL_FUNC) &_VBEMM_H_allprofile_dina, 2},
    {"_VBEMM_H_allprofile_dino", (DL_FUNC) &_VBEMM_H_allprofile_dino, 2},
    {"_VBEMM_H_allprofile_lcdm", (DL_FUNC) &_VBEMM_H_allprofile_lcdm, 4},
    {"_VBEMM_ke_1dim", (DL_FUNC) &_VBEMM_ke_1dim, 3},
    {"_VBEMM_update", (DL_FUNC) &_VBEMM_update, 10},
    {"_VBEMM_update_lcdm", (DL_FUNC) &_VBEMM_update_lcdm, 12},
    {"_VBEMM_ELBO_1dim", (DL_FUNC) &_VBEMM_ELBO_1dim, 14},
    {"_VBEMM_ELBO_lcdm", (DL_FUNC) &_VBEMM_ELBO_lcdm, 16},
    {"_VBEMM_rcpp_hello_world", (DL_FUNC) &_VBEMM_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_VBEMM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
