# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

maipow <- function(a, b) {
    .Call(`_VBEMM_maipow`, a, b)
}

rowprod <- function(a, b) {
    .Call(`_VBEMM_rowprod`, a, b)
}

sigmod <- function(x) {
    .Call(`_VBEMM_sigmod`, x)
}

Sigmod <- function(x) {
    .Call(`_VBEMM_Sigmod`, x)
}

LA1dima <- function(x) {
    .Call(`_VBEMM_LA1dima`, x)
}

LAmatrix <- function(x) {
    .Call(`_VBEMM_LAmatrix`, x)
}

Trans_10to2_mat <- function(K, CL) {
    .Call(`_VBEMM_Trans_10to2_mat`, K, CL)
}

H_allprofile_dina <- function(alfa, Q) {
    .Call(`_VBEMM_H_allprofile_dina`, alfa, Q)
}

H_allprofile_dina_oneitem <- function(alfa, Q) {
    .Call(`_VBEMM_H_allprofile_dina_oneitem`, alfa, Q)
}

H_allprofile_dino <- function(alfa, Q) {
    .Call(`_VBEMM_H_allprofile_dino`, alfa, Q)
}

H_allprofile_lcdm <- function(alfa, Q, comb, leng) {
    .Call(`_VBEMM_H_allprofile_lcdm`, alfa, Q, comb, leng)
}

H_allprofile_oneitem_lcdm <- function(alfa, Q, comb, leng) {
    .Call(`_VBEMM_H_allprofile_oneitem_lcdm`, alfa, Q, comb, leng)
}

ke_1dim <- function(h, lambda, Vlambda) {
    .Call(`_VBEMM_ke_1dim`, h, lambda, Vlambda)
}

update_lcdm <- function(y, h, lambda, Vlambda, xi, phi1, phi2, delta0, delta, rho, lambda0, Vlambda0, lambdaindd, lambdalen) {
    invisible(.Call(`_VBEMM_update_lcdm`, y, h, lambda, Vlambda, xi, phi1, phi2, delta0, delta, rho, lambda0, Vlambda0, lambdaindd, lambdalen))
}

ELBO_1dim <- function(y, Vlambda, xi, rho, Vlambda0, delta, delta0, lambda00, Vlambda00, lambda0t, Vlambda0t, ph0, pht, df) {
    .Call(`_VBEMM_ELBO_1dim`, y, Vlambda, xi, rho, Vlambda0, delta, delta0, lambda00, Vlambda00, lambda0t, Vlambda0t, ph0, pht, df)
}

ELBO_lcdm <- function(y, Vlambda, xi, rho, Vlambda0, delta, delta0, lambdaindd, lambdalen, Mlambda0, VMlambda0, Mlambda0t, VMlambda0t, ph0, pht, df) {
    .Call(`_VBEMM_ELBO_lcdm`, y, Vlambda, xi, rho, Vlambda0, delta, delta0, lambdaindd, lambdalen, Mlambda0, VMlambda0, Mlambda0t, VMlambda0t, ph0, pht, df)
}

ELBO_lcdm_main_inter <- function(y, Vlambda, xi, rho, Vlambda0, delta, delta0, lambdaindd, lambdalen, Mlambda0, VMlambda0, Mlambda0t, VMlambda0t, ph0, pht, df) {
    .Call(`_VBEMM_ELBO_lcdm_main_inter`, y, Vlambda, xi, rho, Vlambda0, delta, delta0, lambdaindd, lambdalen, Mlambda0, VMlambda0, Mlambda0t, VMlambda0t, ph0, pht, df)
}

digamma_vec <- function(a) {
    .Call(`_VBEMM_digamma_vec`, a)
}

Estimate_alpha <- function(rho, alpha_all, N, K) {
    .Call(`_VBEMM_Estimate_alpha`, rho, alpha_all, N, K)
}

VBEMM_DINA <- function(data, K, Q, EMlambda0 = 2, Vlambda0_value = 1, EMeta0 = -1, delta0_value = 1, ueta0 = -2, ulambda0 = 0, veta0 = 10, vlambda0 = 10, Mlambdainitial = 2, Vlambdainitial_value = 1, Metainitial = -1, deltainitial = 1, trunc_num = 0, T = 5000L, e0 = 0.0001) {
    .Call(`_VBEMM_VBEMM_DINA`, data, K, Q, EMlambda0, Vlambda0_value, EMeta0, delta0_value, ueta0, ulambda0, veta0, vlambda0, Mlambdainitial, Vlambdainitial_value, Metainitial, deltainitial, trunc_num, T, e0)
}

VBEMM_DINO <- function(data, K, Q, EMlambda0 = 2, Vlambda0_value = 1, EMeta0 = -1, delta0_value = 1, ueta0 = -2, ulambda0 = 0, veta0 = 10, vlambda0 = 10, Mlambdainitial = 2, Vlambdainitial_value = 1, Metainitial = -1, deltainitial = 1, trunc_num = 0, T = 5000L, e0 = 0.0001) {
    .Call(`_VBEMM_VBEMM_DINO`, data, K, Q, EMlambda0, Vlambda0_value, EMeta0, delta0_value, ueta0, ulambda0, veta0, vlambda0, Mlambdainitial, Vlambdainitial_value, Metainitial, deltainitial, trunc_num, T, e0)
}

VBEMM_LCDM <- function(data, K, Q, lambdaindex, comb, comlen, EMlambda0_value = 2, Vlambda0_value = 1, EMeta0 = -1, delta0_value = 1, ueta0 = -2, ulambda0 = 0, veta0 = 10, vlambda0 = 10, Mlambdainitial = 2, Vlambdainitial_value = 1, Metainitial = -1, deltainitial = 1, T = 5000L, e0 = 0.0001) {
    .Call(`_VBEMM_VBEMM_LCDM`, data, K, Q, lambdaindex, comb, comlen, EMlambda0_value, Vlambda0_value, EMeta0, delta0_value, ueta0, ulambda0, veta0, vlambda0, Mlambdainitial, Vlambdainitial_value, Metainitial, deltainitial, T, e0)
}

VBEMM_LCDM_by_dim <- function(data, K, Q, lambdaindex, comb, comlen, EMlambda0_value = 2, Vlambda0_value = 1, EMeta0 = -1, delta0_value = 1, ueta0 = -2, ulambda0 = 0, veta0 = 10, vlambda0 = 10, Mlambdainitial = 2, Vlambdainitial_value = 1, Metainitial = -1, deltainitial = 1, trunc_num = 0, T = 5000L, e0 = 0.0001) {
    .Call(`_VBEMM_VBEMM_LCDM_by_dim`, data, K, Q, lambdaindex, comb, comlen, EMlambda0_value, Vlambda0_value, EMeta0, delta0_value, ueta0, ulambda0, veta0, vlambda0, Mlambdainitial, Vlambdainitial_value, Metainitial, deltainitial, trunc_num, T, e0)
}

rcpp_hello_world <- function() {
    .Call(`_VBEMM_rcpp_hello_world`)
}

