# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

maipow <- function(a, b) {
    .Call(`_VBEMM_maipow`, a, b)
}

rowprod <- function(a, b) {
    .Call(`_VBEMM_rowprod`, a, b)
}

sigmod <- function(x) {
    .Call(`_VBEMM_sigmod`, x)
}

Sigmod <- function(x) {
    .Call(`_VBEMM_Sigmod`, x)
}

LA1dima <- function(x) {
    .Call(`_VBEMM_LA1dima`, x)
}

LAmatrix <- function(x) {
    .Call(`_VBEMM_LAmatrix`, x)
}

H_allprofile_dina <- function(alfa, Q) {
    .Call(`_VBEMM_H_allprofile_dina`, alfa, Q)
}

H_allprofile_dino <- function(alfa, Q) {
    .Call(`_VBEMM_H_allprofile_dino`, alfa, Q)
}

H_allprofile_lcdm <- function(alfa, Q, comb, leng) {
    .Call(`_VBEMM_H_allprofile_lcdm`, alfa, Q, comb, leng)
}

ke_1dim <- function(h, lambda, Vlambda) {
    .Call(`_VBEMM_ke_1dim`, h, lambda, Vlambda)
}

update <- function(y, h, lambda, Vlambda, xi, phi1, phi2, delta0, lambda0, Vlambda0) {
    .Call(`_VBEMM_update`, y, h, lambda, Vlambda, xi, phi1, phi2, delta0, lambda0, Vlambda0)
}

update_lcdm <- function(y, h, lambda, Vlambda, xi, phi1, phi2, delta0, lambda0, Vlambda0, lambdaindd, lambdalen) {
    .Call(`_VBEMM_update_lcdm`, y, h, lambda, Vlambda, xi, phi1, phi2, delta0, lambda0, Vlambda0, lambdaindd, lambdalen)
}

ELBO_1dim <- function(y, Vlambda, xi, rho, Vlambda0, delta, delta0, Mlambda0, VMlambda0, Mlambda0t, VMlambda0t, ph0, pht, df) {
    .Call(`_VBEMM_ELBO_1dim`, y, Vlambda, xi, rho, Vlambda0, delta, delta0, Mlambda0, VMlambda0, Mlambda0t, VMlambda0t, ph0, pht, df)
}

ELBO_lcdm <- function(y, Vlambda, xi, rho, Vlambda0, delta, delta0, lambdaindd, lambdalen, Mlambda0, VMlambda0, Mlambda0t, VMlambda0t, ph0, pht, df) {
    .Call(`_VBEMM_ELBO_lcdm`, y, Vlambda, xi, rho, Vlambda0, delta, delta0, lambdaindd, lambdalen, Mlambda0, VMlambda0, Mlambda0t, VMlambda0t, ph0, pht, df)
}

rcpp_hello_world <- function() {
    .Call(`_VBEMM_rcpp_hello_world`)
}

